---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: staging
  name: postgresqladmin-claim
spec:
  storageClassName: efs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
