apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31082 # Wybierz port w zakresie 30000-32767
  selector:
    app: angular-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: nginxdemos/hello # Przykładowy obraz Nginx
          ports:
            - containerPort: 80
