apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31081 # Wybierz port w zakresie 30000-32767
  selector:
    app: django-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: tiangolo/uwsgi-nginx:python3.8 # Przykładowy obraz Django z Nginx
          ports:
            - containerPort: 80
