apiVersion: v1
kind: Service
metadata:
  name: memcached-service
spec:
  type: NodePort
  ports:
    - port: 11211
      targetPort: 11211
      nodePort: 31111
  selector:
    app: memcached

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:alpine
          ports:
            - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: phpmemcachedadmin-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31080
  selector:
    app: phpmemcachedadmin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmemcachedadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmemcachedadmin
  template:
    metadata:
      labels:
        app: phpmemcachedadmin
    spec:
      containers:
        - name: phpmemcachedadmin
          image: jacksoncage/phpmemcachedadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: MEMCACHED_HOSTS
              value: memcached-service:11211