apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 31000
  selector:
    app: sonarqube

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:latest
          ports:
            - containerPort: 9000
          env:
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://<db_host>:<db_port>/<db_name>
            - name: SONARQUBE_JDBC_USERNAME
              value: <db_username>
            - name: SONARQUBE_JDBC_PASSWORD
              value: <db_password>
 #         volumeMounts:
 #           - name: sonarqube-data
 #             mountPath: /opt/sonarqube/data
 #           - name: sonarqube-extensions
 #             mountPath: /opt/sonarqube/extensions
 #     volumes:
 #       - name: sonarqube-data
 #         emptyDir: {}
 #       - name: sonarqube-extensions
 #         emptyDir: {}
