apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: artifactory-custom
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      chart: ./HelmCharts/artifactory_prod
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    global:
      masterKey: "cefa6aa6c381a4bebbdfbd2e0c9cb51eebbee172266a0e4d04889cd5c0416c77"
    artifactory:
      initContainers:
        resources:
          requests:
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "50Mi"
            cpu: "10m"
      router:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "100Mi"
          cpu: "100m"
      frontend:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "100Mi"
          cpu: "100m"
      metadata:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "100Mi"
          cpu: "100m"
      event:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "100Mi"
          cpu: "100m"
      observability:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "100Mi"
          cpu: "100m"
      artifactory:
        resources:
          limits:
            memory: "1Gi"
            cpu: "400m"
          requests:
            memory: "1Gi"
            cpu: "400m"
