apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns-custom
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./HelmCharts/external_dns_prod
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    provider: aws
    aws:
      region: eu-north-1
      zoneType: public
    domainFilters:
      - trainingnotes.fit
    policy: sync
    registry: txt
    txtOwnerId: kubemaster
    interval: 1m
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
