apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jenkins-custom
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      chart: ./HelmCharts/jenkins_prod
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    jenkins:
      persistence:
        enabled: true
        existingClaim: "jenkins-claim"
      controller:
        healthProbes: false
        JCasC:
          defaultConfig: false
          configScripts:
            jenkins-casc: |
              {{ .Files.Get "config_scripts/jenkins-casc-config.yaml" }}
        initScripts:
          myInitScript: |-
            {{ (.Files.Get "init_scripts/init.groovy") | indent 4 }}
        serviceType: NodePort
        nodePort: 30007
        resources:
          requests:
            cpu: "600m"
            memory: "1Gi"
          limits:
            cpu: "600m"
            memory: "1Gi"
        agentListenerNodePort: 31113
        agentListenerServiceType: "NodePort"
        agentListenerPort: 31114
        admin:
          username: "admin"
          password: "password"
        installPlugins:
          - prometheus:763.vf8c26b_a_34b_d6
          - git:5.2.2
          - job-dsl:1.87
          - workflow-aggregator:596.v8c21c963d92d
          - configuration-as-code:1807.v0175eda_00a_20
          - kubernetes:4230.vceef11cb_ca_37
          - docker-plugin:1.6.1
          - docker-workflow:572.v950f58993843
          - artifactory:4.0.6
          - sonar:2.17.2
          - pipeline-stage-view:2.34
