apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgresql-custom
  namespace: staging
spec:
  interval: 1m
  chart:
    spec:
      chart: ./HelmCharts/postgresql_prod
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    postgresql:
      primary:
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1Gi
        persistence:
          enabled: true
          existingClaim: "postgresql-claim"
        service:
          type: NodePort
          nodePort: 30008
      metrics:
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        enabled: true
        service:
          type: NodePort
          ports:
            metrics: 9187
            nodePort: 31115
      auth:
        enablePostgresUser: true
        postgresPassword: "bartek"
        username: "bartek"
        password: "bartek"
        database: "postgresql"
